# Learning Scikit-learn
This is a notebook for learning the most populer machine learning librery named **scikit-learn** with the help of a video from freecodecamp - [Link](https://youtu.be/pqNCD_5r0IU)

### What is Scikit-learn?
Scikit-learn is a free software machine learning library for the Python programming language. It features various classification, regression and clustering algorithms including support-vector machines, random forests, gradient boosting, k-means and DBSCAN, and is designed to interoperate with the Python numerical and scientific libraries NumPy and SciPy.
Website - [https://scikit-learn.org/](https://scikit-learn.org/)

# Contents

 - Saving and Opening a Model
 - Train Test Split livr

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Saving and Opening a model

In [2]:
import joblib

In [3]:
model = {"name":"akash"}

# Saving
filename = "test_model.sav"
joblib.dump(model, filename)

['test_model.sav']

In [4]:
# Opening the model
model = joblib.load(filename)
model["name"]

'akash'

## Train test split

In [5]:
from sklearn import datasets
iris= datasets.load_iris()
x=iris.data
y = iris.target
print(x.shape, y.shape)

(150, 4) (150,)


This **train_test_split** model will split the data into in **train** and **test** parts. We will use the **train** part of data to train our model and **test** part to test the accuracy of our model. Here the **test_size = 0.2** part means that 20% of our data will be splitted as test data.

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(120, 4) (120,)
(30, 4) (30,)


## KNN - K-Nearest Neighbors
It is a classification and also a Regression algorithm. ***[Link from scikit-learn](https://scikit-learn.org/stable/modules/neighbors.html#classification)***

The basic nearest neighbors classification uses uniform weights: that is, the value assigned to a query point is computed from a simple majority vote of the nearest neighbors. Under some circumstances, it is better to weight the neighbors such that nearer neighbors contribute more to the fit. This can be accomplished through the weights keyword. The default value, weights = 'uniform', assigns uniform weights to each neighbor. weights = 'distance' assigns weights proportional to the inverse of the distance from the query point. Alternatively, a user-defined function of the distance can be supplied to compute the weights.

In [7]:
from sklearn import neighbors, metrics
from sklearn.preprocessing import LabelEncoder

In [8]:
data = pd.read_csv('data/car.data')
data.head()

buying  maint doors persons lug_boot safety  class
0   high  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [13]:
X = data[['buying', 'maint', 'safety']].values
y = data[['class']]
X = np.array(X)
print(X.shape,y.shape)

(1728, 3) (1728, 1)


Here we will convert our ***labeled data*** into ***Numeric data*** with the help of ***LabelEncoder***

In [14]:
# For converting lebeled data to numerical data
LE = LabelEncoder()
for i in range(len(X[0])):
    X[:, i] = LE.fit_transform(X[:, i])
print(X)

# y labeling with seted data
label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[0 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]
[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-14-8e30e46a6153>:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping)


In [18]:
# Setting datasets
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

# Creating model
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights ="uniform")

# Train model
knn.fit(x_train, y_train)

# Make predictions
predictions = knn.predict(x_test)

# Calculating accuracy
accuracy = metrics.accuracy_score(y_test, predictions)

print(accuracy)

0.7543352601156069


C:\Users\Alamgir\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [23]:
a=1727
print(f"Actual value: {y[a]} . Predicted  value: {knn.predict(X)[a]}")

Actual value: [3] . Predicted  value: 3


In [24]:
# Saving the model
filename = "knn_model.sav"
joblib.dump(model, filename)

['knn_model.sav']